ALTER TABLE countries ADD guide INT DEFAULT NULL;
ALTER TABLE countries ADD CONSTRAINT FK_5D66EBADCA9EC735 FOREIGN KEY (guide) REFERENCES guides (id);
CREATE UNIQUE INDEX UNIQ_5D66EBADCA9EC735 ON countries (guide);
ALTER TABLE guides ADD country VARCHAR(10) DEFAULT NULL;
ALTER TABLE guides ADD CONSTRAINT FK_4D7795EF5373C966 FOREIGN KEY (country) REFERENCES countries (codeCountry);
CREATE UNIQUE INDEX UNIQ_4D7795EF5373C966 ON guides (country);
