fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

main:
    resource: "@MainBundle/Controller/Front/"
    type:     annotation
    prefix:   /

#REST
rest :
    type : rest
    resource: "@MainBundle/Resources/config/routing.yml"

#FOS ROUTING
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#API
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
